Habit_Tracker/Models/ErrorViewModel.cs
using System;

namespace Habit_Tracker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Habit_Tracker/Models/Habit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

//using Microsoft.Data.Sqlite;

namespace Habit_Tracker.Models
{
    public class Habit
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [DisplayName("Weekly Goal")]
        [Required]
        [Range(1,7)]    
        public int WeeklyGoal { get; set; }
        [DisplayName("Current Count")]
        public int CurrentCount { get; set; }
        public bool IsGoalMet { get; set; }
        public DateTime NextReset { get; set; }
    }
}

Habit_Tracker/Controllers/HabitController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Habit_Tracker.Data;
using Habit_Tracker.Models;

namespace Habit_Tracker.Controllers
{
    public class HabitController : Controller
    {
        private readonly ApplicationDbContext _db;

        public HabitController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Habit> habitsList = _db.Habit;
            ResetCount(habitsList);
            return View(habitsList);
        }

        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Habit habit)
        {
            if (ModelState.IsValid)
            {
                habit.NextReset = DateTime.Now.AddDays(7 - (int)DateTime.Now.DayOfWeek);
                _db.Habit.Add(habit);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(habit);
        }

        //GET - TRACK
        public IActionResult Track(int? id)
        {

            if(id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Habit.Find(id);

            if(obj == null)
            {
                return NotFound();
            }

            obj.CurrentCount++;

            if(obj.CurrentCount >= obj.WeeklyGoal)
            {
                obj.IsGoalMet = true;
            }

            _db.Habit.Update(obj);
            _db.SaveChanges();
            
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Habit.Find(id);

            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Habit habit)
        {
            if(ModelState.IsValid)
            {
                _db.Habit.Update(habit);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(habit);
        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Habit.Find(id);

            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Habit.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
                _db.Habit.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
        }

        public void ResetCount(IEnumerable<Habit> habitsList)
        {
            var date = DateTime.Today.Date;
            foreach (Habit habit in habitsList)
            {
                if(DateTime.Compare(date, habit.NextReset) >=0 )
                { 
                    habit.NextReset = DateTime.Now.AddDays(7 - (int)date.DayOfWeek);
                    habit.CurrentCount = 0;
                    _db.Habit.Update(habit);
                }
            }
            _db.SaveChanges();
        }
    }
}

Habit_Tracker/Controllers/HomeController.cs
using Habit_Tracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Habit_Tracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Habit_Tracker/Views/Habit/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Habit_Tracker.Models.Habit

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add habit</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="WeeklyGoal"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="WeeklyGoal" class="form-control" />
                        <span asp-validation-for="WeeklyGoal" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty ?*@
            </div>
        </div>
    </div>

</form>

@section scripts {

        @{ <partial name="_ValidationScriptsPartial" />}

}

Habit_Tracker/Views/Habit/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Habit_Tracker.Models.Habit

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete habit</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="WeeklyGoal"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="WeeklyGoal" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty ?*@
            </div>
        </div>
    </div>

</form>

@section scripts {

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Habit_Tracker/Views/Habit/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Habit_Tracker.Models.Habit

@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add habit</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="WeeklyGoal"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="WeeklyGoal" class="form-control" />
                        <span asp-validation-for="WeeklyGoal" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty ?*@
            </div>
        </div>
    </div>

</form>

@section scripts {

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Habit_Tracker/Views/Habit/Index.cshtml
@model IEnumerable<Habit_Tracker.Models.Habit>

@{
    ViewData["Title"] = "Habit Tracker";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Habit List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Habit" asp-action="Create" class="btn btn-primary">
                Add a New Habit
            </a>
        </div>
    </div>

    <br/><br/>

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Habit Name
                    </th>
                    <th>
                        Weekly Goal
                    </th>
                    <th>
                        Current Count
                    </th>
                    <th>
                        Weekly Goal Met?
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var obj in Model)
                {
                    <tr>
                        <td width="40%">@obj.Name</td>
                        <td width="15%">@obj.WeeklyGoal</td>
                        <td width="15%">@obj.CurrentCount</td>
                        <td width="10%">@obj.IsGoalMet</td>
                        <td width ="20%" class="text-center">
                            <div class="w-70 btn-group" role="group">
                                <a asp-controller="Habit" asp-route-Id="@obj.Id" asp-action="Track" class="btn btn-primary mx-2">
                                    Track
                                </a>
                                <a asp-controller="Habit" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-success mx-2">
                                    Edit
                                </a>
                                <a asp-controller="Habit" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Currently not tracking any habits.</p>
    }
</div>

Habit_Tracker/Views/Habit/Track.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Habit_Tracker.Models.Habit

@{
    ViewData["Title"] = "Track";
}

<form method="post">
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-info pl-3">Track habit</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="WeeklyGoal"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="WeeklyGoal" class="form-control" />
                        <span asp-validation-for="WeeklyGoal" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Track" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty ?*@
            </div>
        </div>
    </div>

</form>

@section scripts {

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Habit_Tracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <br/>
    <p>This is my habit tracking app, built with C# and ASP.NET MVC with a SQL Server database.</p>
    <br/>
    @* <p>Still to come:</p>
    <p> - Users</p>
    <p> - Updated UI</p> *@
    @* <br/> *@
    <p>You can either click the Habits tab above or click <a asp-controller="Habit" asp-action="Index" >here</a> to start tracking your habits!</p>
</div>

Habit_Tracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Habit Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Habit Tracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Habit" asp-action="Index">Habits</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Habit_Tracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>